# Generated by Django 2.2.5 on 2020-02-01 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_codeforcecontest'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='MailChoice',
            field=models.CharField(choices=[('codechef', 'Codechef'), ('codeforce', 'Codeforce'), ('both', 'Codeforce and Codechef both')], default='both', max_length=20),
        ),
    ]
