# Generated by Django 2.2.5 on 2020-02-01 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profile_mailchoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='MailChoice',
            field=models.CharField(choices=[('codechef', 'Codechef'), ('codeforce', 'Codeforce'), ('both', 'Codeforce and Codechef both'), ('non', 'non')], default='both', max_length=20),
        ),
    ]
